### ISSUE TITLE
[Feature] If has errors, throw error, and all errors as error message

### ISSUE THREAD

**Issue by xyy94813** [relay-tools/relay-commit-mutation-promise#1]
Why reject an error?
https://eslint.org/docs/rules/prefer-promise-reject-errors

solution: 
```js
onCompleted: function(payload, errors) {
    if (errors && errors.length !== 0) {
        const error = new Error(errors.toString());
        error.payload = payload;
        error.errors = errors;
        reject(error); // or throw error
        return;
    }
    resolve(payload);
},
```

**Comment by xyy94813** [comment]
Is anyone maintaining this repositories? @robrichard

**Comment by robrichard** [comment]
Not sure I understand this issue. As far as I know, only error objects are being rejected

**Comment by xyy94813** [comment]
Yes, only error objects are being rejected. And use not only the first error message returned

**Comment by robrichard** [comment]
@xyy94813 that can be handled by throwing in your network layer whenever you receive errors from GraphQL. I think this is the recommended approach for relay network layers and its what [react-relay-network-layer](https://github.com/relay-tools/react-relay-network-layer) does by default.

Since this is such a simple abstraction, I don't really want to have churn of breaking changes.

**Comment by xyy94813** [comment]
But the breaking changes is worth.
When use async function and `try catch` , reject an Error instance is more elegant.

Or, maybe we can provide a switch to control whether reject an Error.
